spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/${DOCKER_CUSTOMER_POSTGRES_DB_NAME}
  liquibase:
    url: jdbc:postgresql://localhost:5434/${DOCKER_CUSTOMER_POSTGRES_DB_NAME}
server:
  port: 8100

service:
  document:
    url: localhost:8020