spring:
  application:
    name: resource-service
  profiles:
    active: ${DOCKER_RESOURCE_PROFILES_ACTIVE}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://resource-postgres:${DOCKER_RESOURCE_POSTGRES_DB_PORT}/${DOCKER_RESOURCE_POSTGRES_DB_NAME}
    username: ${DOCKER_RESOURCE_POSTGRES_DB_USER_NAME}
    password: ${DOCKER_RESOURCE_POSTGRES_DB_USER_PASSWORD}
  liquibase:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://resource-postgres:${DOCKER_RESOURCE_POSTGRES_DB_PORT}/${DOCKER_RESOURCE_POSTGRES_DB_NAME}
    user: ${DOCKER_RESOURCE_POSTGRES_DB_USER_NAME}
    password: ${DOCKER_RESOURCE_POSTGRES_DB_USER_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: ${DOCKER_EUREKA_SERVER_HOST}:${DOCKER_EUREKA_SERVER_PORT}/eureka

management:
  endpoints:
    web:
      exposure:
        include: prometheus

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
  api-docs:
    path: /v3/api-docs
